### PR TITLE
Don't equate sex and gender :)

### PR DESCRIPTION
**Pull request by gobengo**
I don't know if this was in an upstream context (which I searched for).

But if it is, please point me to it.

### CODE REVIEW

**Comment by cwebber** [comment]
Thanks, I'm just importing the upstream vocabulary from the Microformats people.  I'd be happy to see this change upstream.

https://github.com/w3c-social/Social-Syntax-Brainstorming/wiki/jf2
http://microformats.org/

Unfortunately I don't have control over it because it's not my standard... any changes you can get to happen upstream I'm interested in happening locally.

**Comment by cwebber** [comment]
Feel free to reopen once you have that done and this becomes actionable for us.

**Comment by wilkie** [comment]
the vCard spec has an enumerated gender ('vCard:hasGender') for some reason. I think it only allows "Male", "Female", and "Other" which aligns it with the common (and, yeah, bizarre) connotations with 'sex' instead. MF2 has 'p-gender-identity' which is freeform, which I guess is already in the json-ld context. It's not a problem if the vCard method is just generally discouraged.

**Comment by dissolve** [comment]
This was originally from p-sex from http://microformats.org/wiki/h-card
I had received a large update to make it work better with as2, i'll make sure to fix this when I move to a new repo for JF2

**Comment by dissolve** [comment]
updated to a new repo for json-ld context, may want to re-open to make sure to update reference to new context

**Comment by kevinmarks** [comment]
That model is not vCard. It has a well-specified gender model that allows free-form text for gender and a sex component:

https://tools.ietf.org/html/rfc6350#section-6.2.7

**Comment by kevinmarks** [comment]
h-card maps this correctly with p-sex and p-gender-identity - looks like the w3c card RDF spec has mapped only the biological Sex component of https://tools.ietf.org/html/rfc6350#section-6.2.7  and called it Gender. That needs fixing, as it is completely against the intent of the gender model in vcard.

How do we file a bug on http://www.w3.org/TR/vcard-rdf/ ?

**Pull request closed without merging**
